# Generated by Django 5.1 on 2024-08-24 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_contactus_remove_user_mobile_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactus",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="contactus",
            old_name="last_name",
            new_name="subject",
        ),
    ]
